# Generated by Django 2.2.3 on 2019-07-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0002_auto_20190713_2242'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encurtador',
            options={'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
        migrations.AlterField(
            model_name='encurtador',
            name='url_hash',
            field=models.SlugField(default='', max_length=80, unique=True),
        ),
    ]
