# Generated by Django 2.2.3 on 2019-07-14 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0003_auto_20190714_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encurtador',
            old_name='url_hash',
            new_name='slug',
        ),
    ]
